### ISSUE TITLE
About winrate graph related

### ISSUE THREAD

**Issue by wonsiks** [hope366/Lizzie-improvements#5]
It seems that changing winrate graph when clicking mouse wheel button doesn't work in this version(v2.1) which was included from v1.8.
Please check this.

Thank you for your work...:)

**Comment by hope366** [comment]
The mouse wheel buttons have the function of enlarging ⇔ reducing them when clicked on the winning percentage graph or sub-board.
It works in v2.1 in my environment ...
Does that mean that it may not work depending on the PC environment?

**Comment by wonsiks** [comment]
@hope366 I'm not sure if it depends on PC env. but  winrate graph doesn't change with wheel button in my PC.
Sub-board is okay. It works fine.

**Comment by wonsiks** [comment]
@hope366 And I've found that mouse wheel button drag on main board can set analysis area.
It's more convenient than alt+mouse drag.

**Comment by hope366** [comment]
Well, I'm not sure, but I guess the mouse wheel buttons have some other function assigned to them.
Isn't that the reason why you can specify the analysis area by dragging the mouse wheel button?
In my PC environment, it is not possible to specify the analysis area by dragging the mouse wheel button.
But it would certainly be very useful to be able to do this.

**Comment by wonsiks** [comment]
@hope366 Oh, it's a bit weird.
I have another question.
Is it right that your jar compile date is 13th December? It's earlier than your release date of v2.1.

**Comment by hope366** [comment]
I compiled it on December 13th, but I wanted to match it with the release of KaTrain-v1.7.0, so I released Lizzie-improved-v2.1 on December 19th.

**Comment by hope366** [comment]
I downloaded the jar file immediately after compilation (updated December 13th) and the released v2.1 jar file and tried to verify it. 
* You can switch the winning percentage graph with the button on the mouse wheel.
* Analysis area cannot be specified by dragging the mouse wheel button

In these two points, both jar files gave the same result.
This is a natural result since no changes have been made from the time it was compiled to the time of release.

**Comment by wonsiks** [comment]
@hope366 Thanks for your kind reply.
I still can't know wny it works differently in my PC at version 2.1.
It's working fine in version 2.0 though.

**Comment by hope366** [comment]
I have little knowledge of computer programming, and I use the pull request published by @kaorahi san in the official version of lizzie for almost all of Lizzie-improvements.
So I'll raise this issue in lizzie's Issues.

**Comment by wonsiks** [comment]
Thank you for solving this issue.
So closing this issue.
